export const LanguageElementsList = [
  { uri: require("../assets/flags/united-kingdom.png"), code: `en-GB` },
  { uri: require("../assets/flags/spain.png"), code: `es-ES` },
  { uri: require("../assets/flags/germany.png"), code: `de-DE` },
  { uri: require("../assets/flags/poland.png"), code: `pl-PL` },
  { uri: require("../assets/flags/italy.png"), code: `it-IT` },
];

export const Translations = {
  play: {
    enGB: `play`,
    enUS: `play`,
    plPL: `graj`,
    esES: `juego`,
    itIT: `giocare`,
    deDE: `abspielen`,
  },
  exit: {
    enGB: `exit`,
    enUS: `exit`,
    plPL: `wyjdź`,
    esES: `salga`,
    itIT: `finire`,
    deDE: `beenden`,
  },
  correct: {
    enGB: `Yes, you got that right!`,
    enUS: `Yes, you got that right!`,
    plPL: `Brawo, znakomicie!`,
    esES: `Si lo hiciste genial!`,
    itIT: `Sì, sei stato bravissimo!`,
    deDE: `Ja, das hast du toll gemacht.`,
  },
  incorrect: {
    enGB: `Sorry, that's not it. Try again.`,
    enUS: `Sorry, that's not it. Try again.`,
    plPL: `Niestety nie. Spróbuj ponownie.`,
    esES: `Lo siento, no es eso. Intentar otra vez.`,
    itIT: `Mi dispiace, non è questo. Riprova.`,
    deDE: `Entschuldigung, das ist es nicht. Versuchen Sie es nochmal.`,
  },
  poorOutocome: {
    enGB: `Don't worry! Next time it will get better. Try again.`,
    enUS: `Dont't worry! Next time it will get better. Try again.`,
    plPL: `Nie martw się! Musisz jeszcze troszkę poświczyć.`,
    esES: `Lo siento, no es eso. Intentar otra vez.`,
    itIT: `Mi dispiace, non è questo. Riprova.`,
    deDE: `Entschuldigung, das ist es nicht. Versuchen Sie es nochmal.`,
  },
  medicoreOutocome: {
    enGB: `Not bad! But I'm sure you can do better.`,
    enUS: `Not bad! But I'm sure you can do better.`,
    plPL: `Nieźle, ale na pewno stać cię na więcej!`,
    esES: `Lo siento, no es eso. Intentar otra vez.`,
    itIT: `Mi dispiace, non è questo. Riprova.`,
    deDE: `Entschuldigung, das ist es nicht. Versuchen Sie es nochmal.`,
  },
  goodOutocome: {
    enGB: `Great! You are a tyue spelling master!`,
    enUS: `Great! You are a tyue spelling master!`,
    plPL: `Znakomicie! Jesteś prawdziwym mistrzem literek!`,
    esES: `Lo siento, no es eso. Intentar otra vez.`,
    itIT: `Mi dispiace, non è questo. Riprova.`,
    deDE: `Entschuldigung, das ist es nicht. Versuchen Sie es nochmal.`,
  },
  youScored: {
    enGB: `You scored`,
    enUS: `You scored`,
    plPL: `Zdobyłeś`,
    esES: `Tienes`,
    itIT: `Hai`,
    deDE: `Du hast`,
  },
  points: {
    enGB: `points`,
    enUS: `points`,
    plPL: `punktów`,
    esES: `puntos`,
    itIT: `punti`,
    deDE: `Punkte`,
  },
};
